THCC/bookings/urls.py
from django.conf.urls import *
#from django.views.generic.simple import *
from views import *
# Enable admin
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^upcoming$', booking_upcoming, name='booking_upcoming'),
    url(r'^booking/(?P<pk>[0-9]+)$', booking_detail, name='booking_detail'),
    url(r'^delete/(?P<pk>[0-9]+)$', booking_deleted, name='booking_deleted'),
    url(r'^calendar$', booking_calendar, name='booking_calendar'),
    url(r'^submit$', booking_submit, name='booking_submit'),
    url(r'^approve$', booking_approvals, name='booking_approvals'),
    url(r'^mine$', booking_mine, name='booking_mine'),
    url(r'^howto$', howto, name='howto'),
)

THCC/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template

from views import *


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

urlpatterns += patterns('',

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))
                        
    # Reservations 
#     url(r'^reservations/', include('reservations.urls')),
#     url(r'^mycalendar', mycalendar_view, name='mycalendar'),
    url(r'^bookings/', include('bookings.urls')),

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

THCC/bookings/models.py
from django.db import models
from django.contrib.auth.models import User


class Booking(models.Model):
    """Booking model - when, where and who"""
    # Which user/group created this booking
    user = models.ForeignKey(User)
    # Event title, reason etc
    title = models.CharField(null=False, max_length=200)
    # Event desc
    desc = models.TextField(null=False)
    # When the booking starts - should be in half hour intervals
    start_date = models.DateTimeField(null=False, blank=False)
    # When the booking period ends
    end_date = models.DateTimeField(null=False, blank=False)
    # When the booking was created - could be useful for conflict resolution, billing etc
    created = models.DateTimeField(auto_now_add=True)
    # Which room/resource was booked
    ROOM_CHOICES = [
        ("Hall", "Hall"),
        ("Kitchen", "Kitchen"),
        ("Lounge", "Lounge"),
        ("Office One", "Office One"),
    ]
    room = models.CharField(null=False, max_length=100, choices=ROOM_CHOICES)
    # Has this booking been approved by an admin
    approved = models.BooleanField(default=False, editable=True)
    # Will the booking appear in Public Events
    public = models.BooleanField(default=False, editable=True)
    # Is this part of a block booking
    block_booking = models.IntegerField(default=0)
    
#     class Meta:
#         abstract = True

    def __unicode__(self):
        return str(self.start_date) + " Title: " + self.title + ", User: " + str(self.user) + ", Room: " + self.room

    def short_desc(self):
        """Default short description visible on reservation button"""
        return str(self.id)

    def to_json(self):
        bookingdict = self.__dict__.copy()  # copy or we modify object's _state etc
        bookingdict['start_date'] = bookingdict['start_date'].strftime("%Y-%m-%dT%H:%M:%S")  # format required by calendar
        bookingdict['end_date'] = bookingdict['end_date'].strftime("%Y-%m-%dT%H:%M:%S")  # format required by calendar
        bookingdict['created'] = ""
        bookingdict['_state'] = ""
#         print bookingdict
        return bookingdict
        
        

THCC/bookings/forms.py
from django import forms
from django.forms.forms import BoundField
from django.template import Context, loader
from .models import Booking

class BookingForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ('title', 'desc', 'start_date', 'end_date', 'room','public',)
        
        

class TemplatedForm(forms.ModelForm):
    '''
    From http://djangosnippets.org/snippets/121/
    '''
    def output_via_template(self):
        """Helper function for fieldsting fields data from form"""

        bound_fields = [BoundField(self, field, name) for name, field \
                        in self.fields.items()]

        c = Context(dict(form=self, bound_fields=bound_fields))
        t = loader.get_template('forms/form.html')
        return t.render(c)

    def __unicode__(self):
        return self.output_via_template()

THCC/bookings/views.py
import uuid
from datetime import datetime, timedelta
from django.shortcuts import render, get_object_or_404, redirect
from models import Booking
from forms import BookingForm
from json import dumps
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import user_passes_test, login_required
from django.views.decorators.csrf import csrf_exempt


def admin_check(user):
    return user.is_staff

@user_passes_test(admin_check)
@csrf_exempt  # until I figure out how to get CSRF working with JS
def booking_approvals(request):     
    if request.method == "POST":
        is_approved = request.POST.get('approved')
        booking_ID = request.POST.get('ID')
        if "no" == is_approved:
            booking_to_delete = Booking.objects.filter(id=booking_ID)
            if len(booking_to_delete) == 0:  # if already rejected, just carry on as normal
                return redirect('bookings.views.booking_approvals')
            # This booking has been rejected - delete it so someone else can use this timeslot
            booking_to_delete[0].delete()
            # TODO: Send rejection email
        if "yes" == is_approved:
            booking_to_approve = Booking.objects.filter(id=booking_ID)[0]
            booking_to_approve.approved = True
            booking_to_approve.save()
            # TODO: Send approval email
    bookings_needing_approval = Booking.objects.filter(approved=False).filter(start_date__gte=datetime.now())
    return render(request, "approvals.html", {'bookings': bookings_needing_approval})

@login_required
def booking_mine(request):     
    bookings_for_user = Booking.objects.filter(user=request.user)
    return render(request, "mine.html", {'bookings': bookings_for_user})

def howto(request):     
    return render(request, "howto.html")

@login_required
def booking_calendar(request):
    """
    Calendar widget requires booking objects as json. We get all bookings from DB, then convert them to json.
    This conversion removes several fields from the Booking object, since they cannot be converted to json/aren't required.
    """
    bookings = Booking.objects.all()  # Todo: should load only this month's bookings
    bookings_as_dicts = []
    for booking in bookings:
        bookings_as_dicts.append(booking.to_json())
    bookings_json_string = dumps(bookings_as_dicts)
    form = BookingForm()
    return render(request, "calendar.html", {'bookings': bookings_json_string, 'form': form})

@login_required
def booking_submit(request):
    if request.method == "POST":
        form = BookingForm(request.POST)
        if not request.user.is_authenticated():
            return render(request, "booking_submitted.html", {"success":False})
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            
            # Verify that this booking will not conflict with any others
            # ie in the same room, with overlapping times
            # to do this quickly, find all bookings in same room, excluding those with start date after new end date and end date before new start date. This makes sense, I promise... 
            conflicting_bookings = Booking.objects.filter(room=booking.room).exclude(start_date__gte=booking.end_date).exclude(end_date__lte=booking.start_date)
            print conflicting_bookings
            if len(conflicting_bookings) > 0:
                print "conflicts found"
                return render(request, "booking_submitted.html", {"success":False})    
            print "no conflicts"
            booking.save()
            # block bookings - adds copies of the booking for x number of weeks. TODO conflict res
            if request.POST['repeat'] == "10times":
                print "block booking"
                block_id = uuid.uuid4().int
                for i in range(1,10):
                    form = BookingForm(request.POST)
                    booking = form.save(commit=False)
                    booking.user = request.user
                    booking.start_date += timedelta(days=7*i)
                    booking.block_booking = block_id 
                    booking.save()
            print booking
            return render(request, "booking_submitted.html", {"success":True})
        return render(request, "booking_submitted.html", {"success":False})
    else:
        return redirect('bookings.views.booking_calendar')

# 
def booking_upcoming(request):
    bookings = Booking.objects.filter(start_date__gte=datetime.now()).filter(approved=True).filter(public=True)
    return render(request, "booking_upcoming.html", {'bookings': bookings})

def booking_detail(request, pk):
    print "view details..."
    booking = get_object_or_404(Booking, pk=pk)
    return render(request, "booking_details.html", {'booking': booking})

def booking_deleted(request, pk):
    print "bye bye"
    # booking_to_delete = get_object_or_404(Booking, pk=pk)
    try:
        booking_to_delete = Booking.objects.get(pk=pk)
    except Booking.DoesNotExist:
        return render(request, "booking_deleted.html", {"success":False})
    if booking_to_delete.user == request.user:
        booking_to_delete.delete()
        return render(request, "booking_deleted.html", {"success":True})
    else:
        return render(request, "booking_deleted.html", {"success":False})

THCC/bookings/templates/forms/calendar_booking.html
<div class="container-fluid">
  <div class="row">
      <div class="col-md-6">
        <h1>New booking:</h1>
        <p>(for more information about the booking process, please see our <a href="/bookings/howto">'How To' guide </a>)</p>
      </div>
  </div>
    
  <form method="POST" class="post-form" action="{% url 'bookings.views.booking_submit' %}">{% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <p><label for="id_title">Title:</label> <input id="id_title" maxlength="200" name="title" type="text" /></p>
    </div>
    <div class="col-md-4">
      <p><label for="id_desc">Description:</label> <input id="id_desc" maxlength="200" name="desc" type="text" /></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <p><label for="id_start_date">Start:</label> <input id="id_start_date" maxlength="200" name="start_date" type="text" /></p>
    </div>
    <div class="col-md-4">
      <p><label for="id_end_date">End:</label> <input id="id_end_date" maxlength="200" name="end_date" type="text" /></p>
    </div>
    <div class="col-md-4">
        <p><label for="id_room">Room:</label> <input id="id_room" maxlength="200" name="room" type="text" /></p>
    </div>
    <div class="col-md-4">
      <p><label for="id_public">Show event in <a href="/bookings/upcoming">Public Events</a> list?: </label> <select id="id_public" name="public">
  <option value="True">Yes</option>
  <option value="False" selected>No</option>
</select></p>
    </div>
      <div class="col-md-4">
<p><label for="id_repeat">Repeat:</label> <select id="id_repeat" name="repeat">
  <option value="once" selected>Once</option>
  <option value="10times">10 times</option>
</select></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <button type="submit" class="save btn btn-default">Save</button>
    </div>
  </div>
  </form>
</div>

<!-- <form method="POST" class="post-form"><input type='hidden' name='csrfmiddlewaretoken' value='yaAClHvb0ZJqBkTUEp4tqkliUuN5IfXR' />
    <p><label for="id_title">Title:</label> <input id="id_title" maxlength="200" name="title" type="text" /></p>
<p><label for="id_desc">Desc:</label> <textarea cols="40" id="id_desc" name="desc" rows="10">
</textarea></p>
<p><label for="id_start_date">Start date:</label> <input id="id_start_date" name="start_date" type="text" /></p>
<p><label for="id_end_date">End date:</label> <input id="id_end_date" name="end_date" type="text" /></p>
<p><label for="id_room">Room:</label> <select id="id_room" name="room">
<option value="" selected="selected">---------</option>
<option value="Hall">Hall</option>
<option value="Kitchen">Kitchen</option>
<option value="Lounge">Lounge</option>
<option value="Office One">Office One</option>
</select></p>
    <button type="submit" class="save btn btn-default">Save</button>
</form> -->

THCC/bookings/templates/forms/field.html
{% comment %}

{% endcomment %}
<div class="control-group">
	<label class="control-label" for="id_{{ field.name }}">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}:</label>
	<div class="controls">{{ field }}
		<span class="help-inline"></span>
	</div>
</div>

THCC/bookings/templates/forms/form.html
{% for field in bound_fields %}
	{% include "forms/field.html" %}
{% endfor %}